name: Run Python Script on Pull Request

# Trigger the workflow on pull requests
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository to the runner
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Specify the Python version you need

    # Install dependencies if needed
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run your Python script
    - name: Run script
      run: python script.py  # Replace 'your-script.py' with the path to your script

    # Read the output from the file
    - name: Read output
      id: read_output
      run: cat output.txt
      continue-on-error: true

    # Add a comment to the pull request with the output
    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('output.txt', 'utf8');
          github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.issue.number,
            body: `Output of the script:\n\`\`\`\n${output}\n\`\`\``
          });
