
name: Run Python Script on Pull Request

# Trigger the workflow on pull requests
on:
  pull_request:
    types: [opened, synchronized]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: true  # Avoid unnecessary pip version check

      - name: Run script
        id: run_script  # Give an ID to use the output in later steps
        run: |
          output=$(python script.py)
          echo "::set-output name=script_output::$output"

      - name: Comment on PR with script output
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `Output of the script:\n\`\`\`\n${process.env.script_output}\n\`\`\``
            });
